{% set version = '0.6-10' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-medflex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/medflex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/medflex/medflex_{{ version }}.tar.gz
  sha256: bd89a8fe939f3becd71a9dab30fe27fa43c96572d8309d2c1a70633117d4cb33

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix >=1.1_4
    - r-boot >=1.3_8
    - r-car >=2.0_21
    - r-multcomp >=1.3_6
    - r-sandwich >=2.3_2
  run:
    - r-base
    - r-matrix >=1.1_4
    - r-boot >=1.3_8
    - r-car >=2.0_21
    - r-multcomp >=1.3_6
    - r-sandwich >=2.3_2

test:
  commands:
    - $R -e "library('medflex')"           # [not win]
    - "\"%R%\" -e \"library('medflex')\""  # [win]

about:
  home: https://github.com/jmpsteen/medflex
  license: GPL-2.0-only
  summary: Run flexible mediation analyses using natural effect models as described in Lange,
    Vansteelandt and Bekaert (2012) <DOI:10.1093/aje/kwr525>, Vansteelandt, Bekaert
    and Lange (2012) <DOI:10.1515/2161-962X.1014> and Loeys, Moerkerke, De Smet, Buysse,
    Steen and Vansteelandt (2013) <DOI:10.1080/00273171.2013.832132>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec
